spring.application.name=GestionProduit
server.port=9093

# Disable Spring Cloud Config
spring.cloud.config.enabled=false

# JWT Configuration - Valeurs directes
jwt.secret=myJWTSecret
jwt.expiration=86400000

google.ai.api.key=MyAPIKEY
# Eureka
eureka.client.service-url.defaultZone=http://eureka:8761/eureka
eureka.instance.prefer-ip-address=true

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://admin:password@mongodb:27017/vermeg_db?authSource=admin
spring.data.mongodb.database=vermeg_db

# Logging
logging.level.org.springframework.security=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.com.zaxxer.hikari=INFO

# CORS configuration for Angular
spring.web.cors.allowed-origins=http://frontend:80
spring.web.cors.allowed-methods=GET,POST,DELETE,PUT
spring.web.cors.allowed-headers=*
spring.web.cors.max-age=3600
spring.web.cors.allow-credentials=true
