spring:
  application:
    name: gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/vermeg-realm

  cloud:
    gateway:
      routes:
        - id: api-user-service
          uri: lb://GESTIONUSER
          predicates:
            - Path=/api/auth/**,/api/users/**

        - id: api-product-service
          uri: lb://GESTIONPRODUIT
          predicates:
            - Path=/api/produits/**,/api/packs/**,/api/garanties/**,/api/chatbot/**

        - id: api-recommendation-service
          uri: lb://GESTIONRECOMMENDATION
          predicates:
            - Path=/api/recommendations/**

      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "http://localhost:4200"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: INFO