# application-docker.yml
spring:
  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/vermeg_db?authSource=admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/vermeg-realm